spring:
  application:
    name: springboot2-sample-zuul-gateway

server:
  port: 7112

# CSE RPC 的配置项
# 应用名称
APPLICATION_ID: springboot-sample
# 微服务名称和版本号，微服务名称使用Spring Cloud的名称
service_description:
  name: ${spring.application.name}
  version: 1.0.0
# 服务中心的地址
servicecomb:
  service:
    registry:
      address: http://localhost:30100
      instance:
        watch: false
# 对外发布的地址，端口号使用server.port
  rest:
    address: 0.0.0.0:${server.port}
# 线下开发，关闭监控数据上报
  monitor:
    client:
      enable: false
# 处理链配置
  handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance,fault-injection-consumer

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  add-host-header: false
  routes:
    user:
      path: /user/**
      service-id: springboot2-sample-zuul-bussiness