CREATE DATABASE IF NOT EXISTS user_db;

USE user_db;

DROP TABLE IF EXISTS T_USER;

CREATE TABLE `T_USER` (
  `ID`  INTEGER(20) NOT NULL COMMENT '产品ID',
  `USER_NAME`  VARCHAR(20) NOT NULL COMMENT '用户名称',
  `TOTAL_BALANCE`  DECIMAL(16,2) NOT NULL COMMENT '价格',
  `RESERVED`  TINYINT(1) NOT NULL COMMENT '是否预定',
  PRIMARY KEY (`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;
