CREATE DATABASE IF NOT EXISTS hotel_db;

USE hotel_db;

DROP TABLE IF EXISTS T_HOTEL;

CREATE TABLE `T_HOTEL` (
  `ID`  INTEGER(20) NOT NULL,
  `TOTAL_BALANCE`  DECIMAL(16,2) NOT NULL,
  `RESERVED`  TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;
