CREATE DATABASE IF NOT EXISTS product_db;

USE product_db;

DROP TABLE IF EXISTS T_PRODUCT;

CREATE TABLE `T_PRODUCT` (
  `ID`  INTEGER(20) NOT NULL COMMENT '产品ID',
  `PROD_NAME`  VARCHAR(20) NOT NULL COMMENT '产品名称',
  `RESERVED`  TINYINT(1) NOT NULL COMMENT '是否预定',
  `PRICE`  DECIMAL(16,2) NOT NULL COMMENT '价格',
  `SOLD`  TINYINT(1) NOT NULL COMMENT '是否预定',
  `RESERVED_USERID`  INTEGER(20) NOT NULL COMMENT '锁定用户',
  PRIMARY KEY (`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;
