CREATE DATABASE IF NOT EXISTS account_db;

USE account_db;

DROP TABLE IF EXISTS T_ACCOUNT;

CREATE TABLE `T_ACCOUNT` (
  `ID`  INTEGER(20) NOT NULL COMMENT '用户ID',
  `TOTAL_BALANCE`  DECIMAL(16,2) NOT NULL COMMENT '价格',
  `RESERVED`  TINYINT(1) NOT NULL COMMENT '是否预定',
  PRIMARY KEY (`ID`)
)
  ENGINE=InnoDB
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
;
